apiVersion: v1
kind: Namespace
metadata:
  name: lms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-employee
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-employee
  template:
    metadata:
      labels:
        app: lms-employee
    spec:
      containers:
        - name: lms-employee
          image: lms-employee:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: lms-employee
  namespace: lms
spec:
  selector:
    app: lms-employee
  ports:
    - port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-manager
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-manager
  template:
    metadata:
      labels:
        app: lms-manager
    spec:
      containers:
        - name: lms-manager
          image: lms-manager:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: lms-manager
  namespace: lms
spec:
  selector:
    app: lms-manager
  ports:
    - port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-gateway
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-gateway
  template:
    metadata:
      labels:
        app: lms-gateway
    spec:
      containers:
        - name: lms-gateway
          image: lms-gateway:latest
          imagePullPolicy: Never
          env:
            - name: EMPLOYEE_URL
              value: "http://lms-employee.lms.svc.cluster.local:8001"
            - name: MANAGER_URL
              value: "http://lms-manager.lms.svc.cluster.local:8002"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: lms-gateway
  namespace: lms
spec:
  type: NodePort
  selector:
    app: lms-gateway
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-frontend
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-frontend
  template:
    metadata:
      labels:
        app: lms-frontend
    spec:
      containers:
        - name: lms-frontend
          image: lms-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lms-frontend
  namespace: lms
spec:
  type: NodePort
  selector:
    app: lms-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30091
